# Generated by Django 3.2.5 on 2021-07-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_done'],
            },
        ),
    ]
